# Generated by Django 2.2.4 on 2019-08-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmodel',
            name='short_url',
            field=models.TextField(null=True),
        ),
    ]
